In [62]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time
import h5py
from sklearn.model_selection import train_test_split

import pandas
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
import numpy as np

In [63]:
X= pickle.load(open("X.pickle", "rb"))
Y= pickle.load(open("Y.pickle", "rb"))

In [64]:
# tensorboard= TensorBoard(log_dir='logs/{}'.format(NAME))

In [65]:
#scale data
X=X/255

# NAME="temp_forehead".format(int(time.time()))

In [66]:
# scores=[]

# best_svr=SVR(kernel='rbf')
# cv=KFold(n_splits=4, random_state=42, shuffle=False)
# for train_index, test_index in cv.split(X):
#     print("Train Index ", train_index, "\n" )
#     print("Test Index ", test_index)
    
#     X_train, X_test, Y_train, Y_test = X[train_index], X[test_index], Y[train_index], Y[test_index]
#     best_svr.fit(X_train, Y_train)
#     scores.append(best_svr.score(X_test, Y_test))

In [67]:
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [68]:
for train_index,test_index in kf.split(X):
    print (train_index, test_index)

[ 5  6  7  8  9 10 11 12 13] [0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13] [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11 12 13]


In [69]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [70]:
# dense_layers= [0, 1, 2]
# layer_sizes = [32, 64, 128]
# conv_layers = [1, 2, 3]


# for dense_layer in dense_layers:
#     for layer_size in layer_sizes:
#         for conv_layer in conv_layers:
#             NAME= "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
#             print(NAME)
#             tensorboard= TensorBoard(log_dir='logs/{}'.format(NAME))
            
#             model = Sequential()
#             model.add(Conv2D(layer_size,(3,3), input_shape= X.shape[1:]))
#             model.add(Activation("relu"))
#             model.add(MaxPooling2D(pool_size=(2,2)))

#             for l in range(conv_layer-1):
#                 model.add(Conv2D(layer_size,(3,3)))
#                 model.add(Activation("relu"))
#                 model.add(MaxPooling2D(pool_size=(2,2)))

#             model.add(Flatten())

#             for d in range(dense_layer):
#                 model.add(Dense(layer_size))
#                 model.add(Activation("relu"))


# #             model.add(Conv2D(64,(3,3)))
# #             model.add(Activation("relu"))
# #             model.add(MaxPooling2D(pool_size=(2,2)))



# #             model.add(Flatten())
# #             model.add(Dense(64))
# #             model.add(Activation('relu'))

#             model.add(Dense(5))
#             model.add(Activation('softmax'))


#             model.compile(loss="sparse_categorical_crossentropy",optimizer = "adam", metrics= ["sparse_categorical_accuracy"])

#             #change batch size when the data becomes large to somewhere in 20s
#             model.fit(X,Y, batch_size=1, epochs=10, validation_split=0.15, callbacks=[tensorboard])

In [71]:
# 3-conv-1-dense -64-nodes
# layer_size = 64

# model = Sequential()
# model.add(Conv2D(layer_size,(3,3), input_shape= X.shape[1:]))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))

# model.add(Conv2D(layer_size,(3,3)))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))

# model.add(Conv2D(layer_size,(3,3)))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))

# model.add(Flatten())

# model.add(Dense(layer_size))
# model.add(Activation("relu"))

# model.add(Dense(4))
# model.add(Activation('softmax'))


# model.compile(loss="sparse_categorical_crossentropy",optimizer = "adam", metrics= ["sparse_categorical_accuracy"])

# #change batch size when the data becomes large to somewhere in 20s
# model.fit(X,Y, batch_size=1, epochs=10, validation_split=0.15)


# model.save('64x3Cx1D.model')

In [72]:
def get_score (model, X_train, X_test, Y_train, Y_test):
    layer_size = 64

    model = Sequential()
    model.add(Conv2D(layer_size,(3,3), input_shape= X_train.shape[1:]))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Conv2D(layer_size,(3,3)))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Conv2D(layer_size,(3,3)))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Flatten())

    model.add(Dense(layer_size))
    model.add(Activation("relu"))

    model.add(Dense(4))
    model.add(Activation('softmax'))


    model.compile(loss="sparse_categorical_crossentropy",optimizer = "adam", metrics= ["sparse_categorical_accuracy"])

    #change batch size when the data becomes large to somewhere in 20s
    model.fit(X_train,Y_train)
    
    return(model.score(X_test, Y_test))


In [73]:
# model = Sequential()
# model.add(Conv2D(64,(3,3), input_shape= X.shape[1:]))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))


# model.add(Conv2D(64,(3,3)))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))


# model.add(Conv2D(64,(3,3)))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))

# model.add(Conv2D(64,(3,3)))
# model.add(Activation("relu"))
# model.add(MaxPooling2D(pool_size=(2,2)))



# model.add(Flatten())
# model.add(Dense(64))
# model.add(Activation('relu'))

# model.add(Dense(3))
# model.add(Activation('softmax'))


# model.compile(loss="sparse_categorical_crossentropy",optimizer = "adam", metrics= ["sparse_categorical_accuracy"])

# #change batch size when the data becomes large to somewhere in 20s
# model.fit(X,Y, batch_size=1, epochs=10, validation_split=0.15, callbacks=[tensorboard])


In [74]:
get_score(model, X_train, X_test, Y_train, Y_test)

ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {"<class 'int'>"})